name = 'cotrans-wk-gateway-domitworker'
main = 'dist/doMitWorker.mjs'
compatibility_date = '2023-07-09'
compatibility_flags = []
workers_dev = false
usage_model = 'bundled'

[[migrations]]
tag = "v1"
new_classes = ["DOMitWorker"]

[durable_objects]
bindings = [{ name = "doMitWorker", class_name = "DOMitWorker" }]

[[d1_databases]]
binding = "DB"
database_name = "cotrans"
database_id = "5586b253-f5be-44cc-9ae4-284029d78da0"
migrations_dir = "../migrations"
